### ISSUE TITLE
index.html is empty

### ISSUE THREAD

**Issue by rcannood** [GuangchuangYu/GuangchuangYu.github.io#2]
Hello @GuangchuangYu!

When I browse your web page, the index page is empty.

Commit 963faf78e88e8160860fdffa847c811da5f1250c seems to have removed all of the content from your index.html ([see changes](https://github.com/GuangchuangYu/GuangchuangYu.github.io/commit/963faf78e88e8160860fdffa847c811da5f1250c#diff-eacf331f0ffc35d4b482f1d15a887d3bL186-L204)).

I assume these changes were unintentional, and you might want to regenerate your page.

Kind regards,
Robrecht

**Comment by GuangchuangYu** [comment]
it is hard to catch the change of the academic hugo theme. 

now I merge the English blog and Chinese blog into one.
